----------------------------------------------------------------------------
-- W205 Section 5 Course Project
-- Vincent Chu
-- File name: load_weather_data.sql
-- Description: 
-- Date       : 11/13/2016
----------------------------------------------------------------------------
drop table ghi_raw;

create external table ghi_raw
(county string,
state string,
county_fips string,
annual_average string,
annual_average_minimum string,
annual_average_maximum string,
annual_average_standard_deviation string,
annual_average_median string,
january_average string,
january_average_minimum string,
january_average_maximum string,
january_average_standard_deviation string,
january_average_median string,
february_average string,
february_average_minimum string,
february_average_maximum string,
february_average_standard_deviation string,
february_average_median string,
march_average string,
march_average_minimum string,
march_average_maximum string,
march_average_standard_deviation string,
march_average_median string,
april_average string,
april_average_minimum string,
april_average_maximum string,
april_average_standard_deviation string,
april_average_median string,
may_average string,
may_average_minimum string,
may_average_maximum string,
may_average_standard_deviation string,
may_average_median string,
june_average string,
june_average_minimum string,
june_average_maximum string,
june_average_standard_deviation string,
june_average_median string,
july_average string,
july_average_minimum string,
july_average_maximum string,
july_average_standard_deviation string,
july_average_median string,
august_average string,
august_average_minimum string,
august_average_maximum string,
august_average_standard_deviation string,
august_average_median string,
september_average string,
september_average_minimum string,
september_average_maximum string,
september_average_standard_deviation string,
september_average_median string,
october_average string,
october_average_minimum string,
october_average_maximum string,
october_average_standard_deviation string,
october_average_median string,
november_average string,
november_average_minimum string,
november_average_maximum string,
november_average_standard_deviation string,
november_average_median string,
december_average string,
december_average_minimum string,
december_average_maximum string,
december_average_standard_deviation string,
december_average_median string)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES (
"separatorChar" = ",",
"quoteChar" = '"',
"escapeChar" = '\\'
)
STORED AS TEXTFILE
location '/user/w205/proj/ghi_data';

drop table dni_raw;

create external table dni_raw
(county string,
state string,
county_fips string,
annual_average string,
annual_average_minimum string,
annual_average_maximum string,
annual_average_standard_deviation string,
annual_average_median string,
january_average string,
january_average_minimum string,
january_average_maximum string,
january_average_standard_deviation string,
january_average_median string,
february_average string,
february_average_minimum string,
february_average_maximum string,
february_average_standard_deviation string,
february_average_median string,
march_average string,
march_average_minimum string,
march_average_maximum string,
march_average_standard_deviation string,
march_average_median string,
april_average string,
april_average_minimum string,
april_average_maximum string,
april_average_standard_deviation string,
april_average_median string,
may_average string,
may_average_minimum string,
may_average_maximum string,
may_average_standard_deviation string,
may_average_median string,
june_average string,
june_average_minimum string,
june_average_maximum string,
june_average_standard_deviation string,
june_average_median string,
july_average string,
july_average_minimum string,
july_average_maximum string,
july_average_standard_deviation string,
july_average_median string,
august_average string,
august_average_minimum string,
august_average_maximum string,
august_average_standard_deviation string,
august_average_median string,
september_average string,
september_average_minimum string,
september_average_maximum string,
september_average_standard_deviation string,
september_average_median string,
october_average string,
october_average_minimum string,
october_average_maximum string,
october_average_standard_deviation string,
october_average_median string,
november_average string,
november_average_minimum string,
november_average_maximum string,
november_average_standard_deviation string,
november_average_median string,
december_average string,
december_average_minimum string,
december_average_maximum string,
december_average_standard_deviation string,
december_average_median string)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES (
"separatorChar" = ",",
"quoteChar" = '"',
"escapeChar" = '\\'
)
STORED AS TEXTFILE
location '/user/w205/proj/dni_data';