----------------------------------------------------------------------------
-- W205 Section 5 Course Project
-- Vincent Chu
-- File name: load_solar_data.sql
-- Description: 
-- Date       : 11/6/2016
----------------------------------------------------------------------------
drop table interconnection_raw;

create external table interconnection_raw
(application_id string,
matched_csi_application_number string,
utility string,
service_city string,
service_zip string,
service_county string,
technology_type string,
system_size_dc string,
system_size_ac string,
tilt string,
azimuth string,
mounting_method string,
tracking string,
customer_sector string,
app_received_date string,
app_complete_date string,
app_approved_date string,
self_installer string,
installer_name string,
installer_phone string,
installer_city string,
installer_state string,
installer_zip string,
third_party_owned string,
third_party_owned_type string,
third_party_name string,
pace_financed string,
pace_financier string,
electric_vehicle string,
electric_vehicle_count string,
system_output_monitoring string,
system_output_reports_to_vendor string,
system_output_monitoring_provider string,
total_system_cost string,
itc_cost_basis string,
vnem_nem_v_nem_agg string,
previous_application string,
previous_application_ids string,
nem_tariff string,
application_status string,
project_is_vnem_nem_v_nem_agg string,
module_model_1 string,
module_manufacturer_1 string,
module_quantity_1 string,
module_model_2 string,
module_manufacturer_2 string,
module_quantity_2 string,
module_model_3 string,
module_manufacturer_3 string,
module_quantity_3 string,
module_model_4 string,
module_manufacturer_4 string,
module_quantity_4 string,
module_model_5 string,
module_manufacturer_5 string,
module_quantity_5 string,
module_model_6 string,
module_manufacturer_6 string,
module_quantity_6 string,
module_model_7 string,
module_manufacturer_7 string,
module_quantity_7 string,
module_model_8 string,
module_manufacturer_8 string,
module_quantity_8 string,
module_model_9 string,
module_manufacturer_9 string,
module_quantity_9 string,
module_model_10 string,
module_manufacturer_10 string,
module_quantity_10 string,
inverter_model_1 string,
inverter_manufacturer_1 string,
inverter_quantity_1 string,
inverter_model_2 string,
inverter_manufacturer_2 string,
inverter_quantity_2 string,
inverter_model_3 string,
inverter_manufacturer_3 string,
inverter_quantity_3 string,
inverter_model_4 string,
inverter_manufacturer_4 string,
inverter_quantity_4 string,
inverter_model_5 string,
inverter_manufacturer_5 string,
inverter_quantity_5 string,
inverter_model_6 string,
inverter_manufacturer_6 string,
inverter_quantity_6 string,
inverter_model_7 string,
inverter_manufacturer_7 string,
inverter_quantity_7 string,
inverter_model_8 string,
inverter_manufacturer_8 string,
inverter_quantity_8 string,
inverter_model_9 string,
inverter_manufacturer_9 string,
inverter_quantity_9 string,
inverter_model_10 string,
inverter_manufacturer_10 string,
inverter_quantity_10 string,
inverter_model_11 string,
inverter_manufacturer_11 string,
inverter_quantity_11 string,
inverter_model_12 string,
inverter_manufacturer_12 string,
inverter_quantity_12 string,
inverter_model_13 string,
inverter_manufacturer_13 string,
inverter_quantity_13 string,
inverter_model_14 string,
inverter_manufacturer_14 string,
inverter_quantity_14 string)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES (
"separatorChar" = ",",
"quoteChar" = '"',
"escapeChar" = '\\'
)
STORED AS TEXTFILE
location '/user/w205/proj/interconn_data';